/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as AuthenticatedVideosImport } from './routes/_authenticated/videos'
import { Route as AuthenticatedUsersIndexImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedStatistikenIndexImport } from './routes/_authenticated/statistiken/index'
import { Route as AuthenticatedFinleyIndexImport } from './routes/_authenticated/finley/index'
import { Route as AuthenticatedChatsIndexImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedBentIndexImport } from './routes/_authenticated/bent/index'
import { Route as AuthenticatedAppsIndexImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedStatistikenPerformanceDashboardImport } from './routes/_authenticated/statistiken/performance-dashboard'
import { Route as AuthenticatedChatsPerformanceDashboardImport } from './routes/_authenticated/chats/performance-dashboard'

// Create/Update Routes

const AuthenticatedRouteRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedVideosRoute = AuthenticatedVideosImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedStatistikenIndexRoute =
  AuthenticatedStatistikenIndexImport.update({
    id: '/statistiken/',
    path: '/statistiken/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedFinleyIndexRoute = AuthenticatedFinleyIndexImport.update({
  id: '/finley/',
  path: '/finley/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedBentIndexRoute = AuthenticatedBentIndexImport.update({
  id: '/bent/',
  path: '/bent/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedStatistikenPerformanceDashboardRoute =
  AuthenticatedStatistikenPerformanceDashboardImport.update({
    id: '/statistiken/performance-dashboard',
    path: '/statistiken/performance-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedChatsPerformanceDashboardRoute =
  AuthenticatedChatsPerformanceDashboardImport.update({
    id: '/chats/performance-dashboard',
    path: '/chats/performance-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/videos': {
      id: '/_authenticated/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof AuthenticatedVideosImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/chats/performance-dashboard': {
      id: '/_authenticated/chats/performance-dashboard'
      path: '/chats/performance-dashboard'
      fullPath: '/chats/performance-dashboard'
      preLoaderRoute: typeof AuthenticatedChatsPerformanceDashboardImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/statistiken/performance-dashboard': {
      id: '/_authenticated/statistiken/performance-dashboard'
      path: '/statistiken/performance-dashboard'
      fullPath: '/statistiken/performance-dashboard'
      preLoaderRoute: typeof AuthenticatedStatistikenPerformanceDashboardImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/bent/': {
      id: '/_authenticated/bent/'
      path: '/bent'
      fullPath: '/bent'
      preLoaderRoute: typeof AuthenticatedBentIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/finley/': {
      id: '/_authenticated/finley/'
      path: '/finley'
      fullPath: '/finley'
      preLoaderRoute: typeof AuthenticatedFinleyIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/statistiken/': {
      id: '/_authenticated/statistiken/'
      path: '/statistiken'
      fullPath: '/statistiken'
      preLoaderRoute: typeof AuthenticatedStatistikenIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteRouteChildren {
  AuthenticatedVideosRoute: typeof AuthenticatedVideosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedChatsPerformanceDashboardRoute: typeof AuthenticatedChatsPerformanceDashboardRoute
  AuthenticatedStatistikenPerformanceDashboardRoute: typeof AuthenticatedStatistikenPerformanceDashboardRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedBentIndexRoute: typeof AuthenticatedBentIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedFinleyIndexRoute: typeof AuthenticatedFinleyIndexRoute
  AuthenticatedStatistikenIndexRoute: typeof AuthenticatedStatistikenIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedVideosRoute: AuthenticatedVideosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedChatsPerformanceDashboardRoute:
    AuthenticatedChatsPerformanceDashboardRoute,
  AuthenticatedStatistikenPerformanceDashboardRoute:
    AuthenticatedStatistikenPerformanceDashboardRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedBentIndexRoute: AuthenticatedBentIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedFinleyIndexRoute: AuthenticatedFinleyIndexRoute,
  AuthenticatedStatistikenIndexRoute: AuthenticatedStatistikenIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteRouteWithChildren
  '/videos': typeof AuthenticatedVideosRoute
  '/': typeof AuthenticatedIndexRoute
  '/chats/performance-dashboard': typeof AuthenticatedChatsPerformanceDashboardRoute
  '/statistiken/performance-dashboard': typeof AuthenticatedStatistikenPerformanceDashboardRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/bent': typeof AuthenticatedBentIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/finley': typeof AuthenticatedFinleyIndexRoute
  '/statistiken': typeof AuthenticatedStatistikenIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
}

export interface FileRoutesByTo {
  '/videos': typeof AuthenticatedVideosRoute
  '/': typeof AuthenticatedIndexRoute
  '/chats/performance-dashboard': typeof AuthenticatedChatsPerformanceDashboardRoute
  '/statistiken/performance-dashboard': typeof AuthenticatedStatistikenPerformanceDashboardRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/bent': typeof AuthenticatedBentIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/finley': typeof AuthenticatedFinleyIndexRoute
  '/statistiken': typeof AuthenticatedStatistikenIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/videos': typeof AuthenticatedVideosRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/chats/performance-dashboard': typeof AuthenticatedChatsPerformanceDashboardRoute
  '/_authenticated/statistiken/performance-dashboard': typeof AuthenticatedStatistikenPerformanceDashboardRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/bent/': typeof AuthenticatedBentIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/finley/': typeof AuthenticatedFinleyIndexRoute
  '/_authenticated/statistiken/': typeof AuthenticatedStatistikenIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/videos'
    | '/'
    | '/chats/performance-dashboard'
    | '/statistiken/performance-dashboard'
    | '/apps'
    | '/bent'
    | '/chats'
    | '/finley'
    | '/statistiken'
    | '/tasks'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/videos'
    | '/'
    | '/chats/performance-dashboard'
    | '/statistiken/performance-dashboard'
    | '/apps'
    | '/bent'
    | '/chats'
    | '/finley'
    | '/statistiken'
    | '/tasks'
    | '/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/videos'
    | '/_authenticated/'
    | '/_authenticated/chats/performance-dashboard'
    | '/_authenticated/statistiken/performance-dashboard'
    | '/_authenticated/apps/'
    | '/_authenticated/bent/'
    | '/_authenticated/chats/'
    | '/_authenticated/finley/'
    | '/_authenticated/statistiken/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated/route.tsx",
      "children": [
        "/_authenticated/videos",
        "/_authenticated/",
        "/_authenticated/chats/performance-dashboard",
        "/_authenticated/statistiken/performance-dashboard",
        "/_authenticated/apps/",
        "/_authenticated/bent/",
        "/_authenticated/chats/",
        "/_authenticated/finley/",
        "/_authenticated/statistiken/",
        "/_authenticated/tasks/",
        "/_authenticated/users/"
      ]
    },
    "/_authenticated/videos": {
      "filePath": "_authenticated/videos.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/chats/performance-dashboard": {
      "filePath": "_authenticated/chats/performance-dashboard.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/statistiken/performance-dashboard": {
      "filePath": "_authenticated/statistiken/performance-dashboard.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/apps/": {
      "filePath": "_authenticated/apps/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/bent/": {
      "filePath": "_authenticated/bent/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/chats/": {
      "filePath": "_authenticated/chats/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/finley/": {
      "filePath": "_authenticated/finley/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/statistiken/": {
      "filePath": "_authenticated/statistiken/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/tasks/": {
      "filePath": "_authenticated/tasks/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/users/": {
      "filePath": "_authenticated/users/index.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
